/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jraceTrack;

import it.unicam.cs.pa.jraceTrack.Model.TrackLocation2D;
import it.unicam.cs.pa.jraceTrack.View.ConsoleView;
import it.unicam.cs.pa.jraceTrack.View.View;

import java.io.IOException;

public class App {



    public static void main(String[] args) throws IOException {
        View<TrackLocation2D> view = new ConsoleView();
        view.open();
    }
}
