/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jraceTrack;

import it.unicam.cs.pa.jraceTrack.Controller.Controller;
import it.unicam.cs.pa.jraceTrack.Model.Location;
import it.unicam.cs.pa.jraceTrack.View.JavaFXManager;
import it.unicam.cs.pa.jraceTrack.View.View;
import javafx.application.Application;

import java.io.IOException;

public class App<L extends Location<L>> {

    private final View<L> view;
    private final Controller<L> controller;

    public App(View <L> view, Controller<L> controller) {
        this.view = view;
        this.controller = controller;
    }

    public static void main(String[] args) throws IOException {
            launchGui();
       /* View<TrackLocation2D> view = new ConsoleView();
        view.open();
        view.close();*/
    }

    private static void launchGui() {
        Application.launch(JavaFXManager.class);
    }

}
